config/routes.rb
Rails.application.routes.draw do
  resources :logs do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  def self.by_recent
    order("created_at DESC")
  end
end

app/models/log.rb
class Log < ApplicationRecord
  enum status: { "Draft" => 0, "Published" => 1 }
  enum motivation: {
    "😫" => 0,
    "😖" => 1,
    "😞" => 2,
    "😕" => 3,
    "🙄" => 4,
    "😐" => 5,
    "🤔" => 6,
    "🙂" => 7,
    "😉" => 8,
    "😆" => 9
  }

  validates_presence_of :round, :day, :content, :status, :motivation, :created_at
  has_many :comments, as: :commentable

  def self.by_recent
    order("created_at DESC")
  end
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :comments, dependent: :destroy

  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @parent = @commentable
    until @parent.is_a?(Log)
      @parent = @parent.commentable
    end
    respond_to do |format|
      if @comment.save
        if @commentable.is_a?(Comment)
          replying_to = @commentable.user
        end
        format.html { redirect_to @parent, notice: 'Your comment was successfully posted.' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Log.find_by_id(params[:log_id]) if params[:log_id]
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show], user: [:index, :show], site_admin: :all

  # GET /logs
  def index
    @all_logs = Log.all
    if Log.count == 0
      @progress = 0
    else
      @progress = Log.last.day
    end
    if logged_in?(:site_admin)
      @logs = Log.by_recent.page params["page"]
    else
      @logs = Log.where(status: 'Published').by_recent.page params["page"]
    end
  end

  # GET /logs/1
  def show
    @comment_count = @log.comments.count
    @comments = @log.comments.by_recent
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  def create
    @log = Log.new(log_params)

    if @log.save
      redirect_to @log, notice: 'Log was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /logs/1
  def update
    if @log.update(log_params)
      redirect_to @log, notice: 'Log was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /logs/1
  def destroy
    @log.destroy
    redirect_to logs_url, notice: 'Log was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def log_params
      params.require(:log).permit(:round, :day, :content, :status, :motivation, :created_at, :completed_minutes, :commits)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg name
    file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
    return File.read(file_path).html_safe if File.exists?(file_path)
    '(not found)'
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:div, msg, class: 'notification is-danger') }.join

    html = <<-HTML
    <div id="error_explanation">
      #{messages}
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end
end

app/helpers/logs_helper.rb
module LogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}"
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)
    
    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true
    }
    
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    
    markdown_to_html.render(text).html_safe
  end

  def humanize mins
    [[60, :minute], [24, :hour], [1000, :day]].map{ |count, name|
      if mins > 0
        mins, n = mins.divmod(count)
        pluralize(n.to_i, "#{name}")
      end
    }.compact.reverse.join(' ')
  end
end

app/views/comments/_comment.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64 comment-avatar">
      <%= gravatar_helper comment.user %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <% if comment.commentable.is_a?(Comment) %>
        <small>Replying to <%= comment.commentable.user.name %></small><br/>
      <% end %>
      <%= markdown comment.content %>
      <br/>
      <small>
        <%= pluralize(comment.comments.count, 'reply') %>
      </small> ·  
      <% if current_user %>
        <button data-commentid="<%= comment.id %>" class="reply button is-primary is-outlined">
        Reply
        </button> ·  
      <% end %>
      <small>
        <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.name %>
      </small>
    </div>
    <% if current_user %>
      <div class="expandme hidden" data-commentid="<%= comment.id %>">
        <%= form_for [comment, Comment.new] do |f| %>
          <div class="field">
            <%= f.label :content, 'Add a reply', class: 'label' %>
            <div class="control">
              <%= f.text_area :content, class: 'textarea' %>
            </div>
          </div>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.submit "Reply", class: 'button is-primary reply-button' %>
        <% end %>
      </div>
    <% end %>
    <%= render partial: 'comments/comment', collection: comment.comments.by_recent %>
  </div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield(:title) %> | Chazona's #100DaysOfCode Log</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@chznbaum">
    <meta name="twitter:creator" content="@chznbaum">
    <meta property="og:url" content="<%= request.url %>">
    <meta property="og:title" content="<%= yield(:title) %>: Chazona's #100DaysOfCode Log">
    <meta property="og:description" content="A day in the log of Chazona Baum">
  </head>

  <body>
    <nav class="navbar is-size-5">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_url, class: 'navbar-item' do %>
            <%= svg 'logo' %>
          <% end %>
          <%= link_to 'Log', logs_path, class: 'navbar-item is-hidden-desktop' %>
        </div>
        <div id="navbarMenu" class="navbar-menu">
          <div class="navbar-start">
            <%= link_to 'Log', logs_path, class: 'navbar-item' %>
            <%= link_to 'About', about_url, class: 'navbar-item' %>
            <%= link_to 'Contact', contact_url, class: 'navbar-item' %>
          </div>
          <div class="navbar-end">
            <span class="navbar-item">
              <% if current_user %>
                <%= link_to 'Log Out', destroy_user_session_url, method: :delete, class: 'button is-primary inverse' %>
              <% else %>
                <%= link_to 'Log In', new_user_session_url, class: 'button is-primary inverse' %>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    </nav>
    <section class="hero is-primary is-medium is-bold">
      <div class="hero-body">
        <div class="container">
          <h1 class="title is-1"><%= yield(:title) %></h1>
        </div>
      </div>
    </section>

    <% if notice %>
      <section class="section">
        <div class="container">
          <div class="notification">
            <%= notice %>
          </div>
        </div>
      </section>
    <% end %>
    <% if alert %>
      <section class="section">
        <div class="container">
          <div class="notification is-warning">
            <%= alert %>
          </div>
        </div>
      </section>
    <% end %>

    <%= yield %>

    <footer class="footer">
      <div class="container">
        <div class="columns">
          <div class="column is-8">
            <div class="content">
              <p>#100DaysOfCode Log by <a href="https://chazonabaum.com">Chazona Baum</a> for challenge created by <a href="http://kallaway.io/">Alexander Kallaway</a>.</p>
              <p><%= link_to 'About Chazona and the #100DaysOfCode Challenge', about_url %></p>
            </div>
          </div>
          <div class="column is-4">
            <div class="content">
              <p><%= link_to 'View Logs', logs_url %></p>
              <p><%= link_to 'Contact Chazona', contact_url %></p>
            </div>
          </div>
        </div>
        <small>
          <p>© 2017 <a href="https://chazonabaum.com">Chazona Baum</a>. All rights reserved.</p>
          <p>Source code available on <a href="https://github.com/chznbaum/hundred-days">GitHub</a>.</p>
        </small>
      </div>
    </footer>
  </body>
</html>

app/views/logs/_form.html.erb
<%= form_with(model: log, local: true) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      
      <% log.errors.full_messages.each do |message| %>

        <div class="notification is-danger">
          <%= message %>
        </div>
      <% end %>

    </div>
  <% end %>

  <div class="field">
    <%= form.label :created_at, 'Log date', class: 'label' %>
    <div class="control">
      <%= form.date_field :created_at, value: (log.created_at || Time.now), class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :round, class: 'label' %>
    <div class="control">
      <%= form.number_field :round, id: :log_round, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :day, class: 'label' %>
    <div class="control">
      <%= form.number_field :day, id: :log_day, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :completed_minutes, class: 'label' %>
    <div class="control">
      <%= form.number_field :completed_minutes, id: :log_completed_minutes, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :commits, class: 'label' %>
    <div class="control">
      <%= form.number_field :commits, id: :log_commits, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :content, class: 'label' %>
    <%= form.text_area :content, id: :log_content, class: 'textarea' %>
  </div>

  <div class="field">
    <div class="control">
      <% Log.statuses.keys.each do |status| %>
        <%= form.radio_button :status, status %>
        <%= form.label "#{status}_#{status.parameterize.underscore}", status.to_sym %>
      <% end %>
    </div>
  </div>

  <div class="field">
    <%= form.label :motivation, class: 'label' %>
    <div class="select is-primary is-large">
      <%= form.select(:motivation, Log.motivations.keys.map {|motivation| [motivation, motivation]}, id: :log_motivation) %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.submit "Submit Log", class: 'button is-primary' %>
    </div>
  </div>
<% end %>

app/views/logs/edit.html.erb
<% provide(:title, "Editing Log from Round #{@log.round} Day #{@log.day}") %>
<section class="section">
  <div class="container">

    <%= render 'form', log: @log %>

    <%= link_to 'Show', @log, class: 'button is-light' %>
    <%= link_to 'Back', logs_path, class: 'button is-light' %>

  </div>
</section>

app/views/logs/index.html.erb
<% provide(:title, "Log") %>

<section class="section">
  <div class="container content is-large">
    <h2>Challenge Progress</h2>
    <progress class="progress is-primary" value="<%= @progress %>" max="100"><%= @progress %>%</progress>
    <p>Total Time: <%= humanize @all_logs.sum("completed_minutes") %></p>
  </div>
  <div class="container">
    <%= paginate @logs %>
  </div>
</section>

<% @logs.each do |log| %>
  <section class="section">
    <div class="container content is-medium">
      <hr>
      <h2><%= link_to "Round #{log.round} Day #{log.day}", log %></h2>
      <p>
        <strong><%= log.status %></strong> <%= distance_of_time_in_words(log.created_at, Time.now) %> ago
        <br>
        <% if log.completed_minutes %>
          <strong>Time:</strong> <%= humanize log.completed_minutes %>
          <br>
        <% end %>
        <% if log.commits %>
          <strong>Commits:</strong> <%= log.commits %>
          <br>
        <% end %>
        <strong>Motivation:</strong> <%= log.motivation %>
        <br>
        <strong>Log:</strong>
      </p>
      <%= markdown log.content %>
      <p>
        <%= link_to 'Show', log, class: 'button is-primary' %>
        <%= link_to 'Edit', edit_log_path(log), class: 'button is-warning' if logged_in?(:site_admin) %>
        <%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' if logged_in?(:site_admin) %>
      </p>
    </div>
  </section>
<% end %>

<section class="section">
  <div class="container">
    <%= paginate @logs %>
    <%= link_to 'New Log', new_log_path, class: 'button is-primary button-group' if logged_in?(:site_admin) %>
  </div>
</section>

app/views/logs/new.html.erb
<% provide(:title, "New Log") %>
<section class="section">
  <div class="container">
    <%= render 'form', log: @log %>

    <%= link_to 'Back', logs_path, class: 'button is-light' %>

  </div>
</section>

app/views/logs/show.html.erb
<% provide(:title, "Round #{@log.round} Day #{@log.day}") %>
<section class="section">
  <div class="container content is-medium">

    <h2>Round <%= @log.round %> Day <%= @log.day %></h2>

    <p>
      <strong><%= @log.status %></strong> <%= distance_of_time_in_words(@log.created_at, Time.now) %> ago
      <br>
      <% if @log.completed_minutes %>
        <strong>Time:</strong> <%= humanize @log.completed_minutes %>
        <br>
      <% end %>
      <% if @log.commits %>
        <strong>Commits:</strong> <%= @log.commits %>
        <br>
      <% end %>
      <strong>Motivation:</strong> <%= @log.motivation %>
      <br>
      <strong>Log:</strong>
    </p>
    <article>
      <%= markdown @log.content %>
    </article>

    <h2>
      <% if @log.comments.count == 0 %>
        Join the Conversation
      <% else %>
        <%= pluralize(@comment_count, 'Comment') %>
      <% end %>
    </h2>
    <% if current_user %>
      <%= form_for [@log, Comment.new] do |f| %>
        <div class="field">
          <%= f.label :content, 'Add a comment', class: 'label' %>
          <div class="control">
            <%= f.text_area :content, class: 'textarea' %>
          </div>
        </div>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.submit "Add comment", class: 'button is-primary' %>
      <% end %>
    <% else %>
      <div class="notification">
        Only logged in users can leave a comment. Would you like to <%= link_to 'login', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %>?
      </div>
    <% end %>

    <div class="margin-top" id="comment-group">
      <%= render(partial: 'comments/comment', collection: @comments) %>
    </div>

    <p class="button-group">
      <%= link_to 'Edit', edit_log_path(@log), class: 'button is-warning' if logged_in?(:site_admin) %>
      <%= link_to 'Back', logs_path, class: 'button is-primary' %>
    </p>

  </div>
</section>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<section class="section">
  <div class="container content is-medium">
    <h2>Chazona Baum</h2>
    <p>Over the past year, I have taught myself as much full-stack web development as my eager mind can take in. Learn more about me at <a href="https://chazonabaum.com/about">my portfolio/blog website</a>.</p>
    <h3>Hire Me</h3>
    <p>I am currently available for employment either remotely or local to the Virginia Beach, Virginia, USA area. My portfolio and <a href="https://github.com/chznbaum">GitHub</a> are great places to check out my work, and I would welcome technical testing via a small take-home project. I can be <a href="https://chazonabaum.com/contact">contacted directly through my portfolio website</a>.</p>
  </div>
</section>
<section class="section">
  <div class="container content is-medium">
    <h2>The #100DaysOfCode Challenge</h2>
    <p>Founded by Alexander Kallaway in 2016, the #100DaysOfCode challenge is a daily promise to code at minimum an hour each day for 100 consecutive days, to tweet the progress and encourage others within the challenge.</p>
    <p>Read <a href="https://medium.freecodecamp.com/join-the-100daysofcode-556ddb4579e4">the article that started it all</a>, <a href="https://medium.freecodecamp.com/start-2017-with-the-100daysofcode-improved-and-updated-18ce604b237b">the revised follow-up article</a>, or learn more at <a href="http://100daysofcode.com">the official 100DaysOfCode website</a>.</p>
  </div>
</section>
<section class="section">
  <div class="container content is-medium">
    <h2>The Stack</h2>
    <p>This site was created using the following technologies and tooling:</p>
    <h3>Front-End</h3>
    <ul>
      <li>ERB</li>
      <li>SCSS</li>
      <li><a href="http://bulma.io/">Bulma</a></li>
      <li><em>Will use JavaScript and Vue.js</em></li>
    </ul>
    <h3>Back-End</h3>
    <ul>
      <li>Rails 5</li>
      <li>PostgreSQL</li>
      <li>Webpack</li>
    </ul>
    <h3>Testing and Deployment</h3>
    <ul>
      <li>Minitest with Fixtures</li>
      <li>Travis CI</li>
      <li>Heroku</li>
    </ul>
    <p>This site is freely-available open-sourced. If you find it useful, please feel free to adapt a copy for your needs and star it on <a href="https://github.com/chznbaum/hundred-days">GitHub</a>.</p>
    <p>Motivation tracking inspired by and adapted from <a href="https://twitter.com/SchnucklePi">@SchnucklePi</a>. Progress bar tracking inspired by and adapted from <a href="https://twitter.com/ChrisVomRhein">@ChrisVomRhein</a>.</p>
  </div>
</section>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<section class="section">
  <div class="container content is-medium">
    <p>Feel free to contact me through <a href="https://chazonabaum.com/contact">my website</a>. This #100DaysOfCode log website is a work-in-progress, so feedback and suggestions are always welcome.</p>
  </div>
</section>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<section class="section">
  <div class="container content is-medium">
    <p>
      This is the home page for <a href="https://chazonabaum.com">Chazona Baum</a>'s log for the #100DaysOfCode challenge.
    </p>
  </div>
</section>